AWSTemplateFormatVersion: '2010-09-09'
Description: Dummy CloudFormation template for testing deploy pipeline

Parameters:
  Environment:
    Type: String
    Default: dummy
    Description: Deployment environment (e.g., dev, staging, prod)

Resources:
  DummyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dummy-bucket-${Environment}

Outputs:
  DummyBucketName:
    Description: Name of the dummy S3 bucket
    Value: !Ref DummyS3Bucket
