name: Create New Instance

on:
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Name of the Instance Repo'
        required: true
        type: string
      instance_name:
        description: 'Name of the new Instance'
        required: true
        type: string
      server:
        description: 'Target Server'
        required: false
        type: string
      bt_cli_branch:
        description: 'bt-cli branch'
        required: true
        type: string

jobs:
  harbor_build:
    uses: brain-tec/ci_workflows/.github/workflows/bt_ci_build_push_harbor.yml@master
    secrets: inherit

  build:
    needs: harbor_build
    runs-on: ubuntu-latest
    steps:
      - name: Install BT-CLI
        id: install_bt_cli
        uses: ./ci_workflows/.github/actions/bt_cli_installation  
        with:
          secret_ACTIONS_READ_TOKEN: ${{ secrets.ACTIONS_READ_TOKEN }}
          secret_ACTIONS_READ_SSH: ${{ secrets.ACTIONS_READ_SSH }}
          bt_cli_branch: ${{ inputs.bt_cli_branch }}

      - name: Create Instance via BT update
        id: create_instance
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_READ_TOKEN }}
        run: |
          bt deploy -m update -s ${{ inputs.server }}.bt-group.com -p ${{ inputs.remote_repo }}:${{ inputs.instance_name }} --no-auto-update

      - name: Send Webhook notification
        if: always()
        run: |
          curl -X POST https://braintec.com/notify_create \
            -H "Content-Type: application/json" \
            -d '{
              "status": "${{ job.status }}",
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "workflow": "${{ github.workflow }}"
            }'

