name: Create New Instance
on:
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Name of the Instance Repo'
        required: true
        type: string
      instance_name:
        description: 'Name of the new Instance'
        required: true
        type: string
      server:
        description: 'Target Server'
        required: false
        type: string

jobs:

#  call-workflow-build-deploy-harbor:
#    name: "Build in Harbor"
#    uses: brain-tec/ci_workflows/.github/workflows/bt_ci_build_push_harbor.yml@master
#    secrets: inherit

  create_instance:
    name: "Create Instance"
    runs-on: ubuntu-latest
#    env:
#      PYTHONUNBUFFERED: 1
#      HARBOR_ROBOT_AUTH: ${{ secrets.HARBOR_GITHUB_ACTION_BT_DOCKER_PULL_USER }}:${{ secrets.HARBOR_GITHUB_ACTION_BT_DOCKER_PULL_PASS }}  # Also for pull
#    if: (github.event_name == 'push' && (contains(github.event.head_commit.message, 'Merge pull request') || contains(github.event.head_commit.message, 'Syncing with commit'))) || github.event_name == 'pull_request'
    steps:
#      - name: "Checkout ci_workflows"
#        uses: actions/checkout@v4
#        with:
#          ref: master
#          token: ${{ secrets.ACTIONS_READ_TOKEN }}
#          repository: brain-tec/ci_workflows.git
#          path: 'ci_workflows'
#
      - name: "Install BT-CLI"
        id: install_bt_cli
        uses: brain-tec/ci_workflows/tree/master/.github/actions/bt_cli_installation
        with:
          secret_ACTIONS_READ_TOKEN: ${{ secrets.ACTIONS_READ_TOKEN }}
          secret_ACTIONS_READ_SSH: ${{ secrets.ACTIONS_READ_SSH }}
#
#      - name: "Create Instance"
#        id: create_instance
#        run: |
#         bt deploy -m update -s ${{ inputs.server }}.bt-group.com -p ${{ inputs.remote_repo }}:${{ inputs.instance_name}}" --no-auto-update

      - name: "Test Message"
        run: |
          echo "Test Message"

      # Always run as last step
      - name: "Send Webhook notification"
        if: always()
        run: |
          curl -X POST https://braintec.com/notify_create \
            -H "Content-Type: application/json" \
            -d '{
              "status": "${{ job.status }}",
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "workflow": "${{ github.workflow }}"
            }'
